#!/bin/bash

COMMAND=$@
DIR=$PWD

function block_for_change {
    inotifywait -q -q -r -e modify $DIR
}

function kill_command {
    # TODO BUG: When $COMMAND contains special regexp chars, like (), pgrep will
    # fail to find the command in the process tree.
    pid=$(pgrep -xf "$COMMAND")
    if [ "$pid" ]; then
        kill -s SIGINT -$pid
    fi
}

function run_command {
        setsid $COMMAND &
}

trap kill_command INT
echo -e ">> Watching for file changes in current directory, press Ctrl+C to stop.\n"
run_command

while block_for_change; do
    kill_command
    run_command
    echo -e "\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n"
    sleep 1 # Sleep and ignore any file changes for a short time (prevents multispawning the $CMD)
done
