#!/bin/sh

# WM Style
bspc monitor primary -d 1 2 3 4 5 6 7 8 9 0
bspc config border_width 1
bspc config focused_border_color "#4c7899"
bspc config window_gap 0
bspc config top_padding 10

# Mouse
bspc config focus_follows_pointer false
bspc config click_to_focus any
bspc config swallow_first_click true

# WM behaviour
bspc config split_ratio 0.5
bspc config automatic_scheme longest_side
#bspc config initial_polarity second_child
bspc config ignore_ewmh_focus true
bspc config ignore_ewmh_fullscreen all

# Custom behaviour for apps
bspc rule -a Firefox desktop='^1'
bspc rule -a Peek state=floating center=true

