#!/bin/bash

Clock() {
        DATETIME=$(date "+%Y-%m-%d %H:%M:%S")
        echo -n "$DATETIME"
}

Desktop() {
        DESKTOP=$(bspc query --names --desktops -d focused)
        echo -n "$DESKTOP"
}

Window() {
        ID=$(xprop -root _NET_ACTIVE_WINDOW | cut -d " " -f 5)
        if [ "$ID" != "0x0" ]; then
                WINDOW=$(xprop -id $ID _NET_WM_NAME | awk -F '"' '{print $2}')
                echo -n "$WINDOW"
        fi
}

while true; do
        echo "%{l}$(Desktop) %{c}$(Window) %{r}$(Clock)"
        sleep 1
done
